#!/bin/perl
use File::Spec::Functions;
use File::Basename;
use File::Copy;
use Cwd 'realpath';
use Switch;

#MAIN
if( @ARGV != 1 ) {
	print "Whoa there, not the right number of arguments. I was expecting ONE.\n";
	exit;
}

switch ($ARGV[0]) {
	case "--help" { displayHelp(); }
	case "push" { doArtPush(); exit; }
	case "pull" { doArtPull(); exit; }
	case "sync" { doArtPull(); doArtPush(); exit;}
	else { displayHelp(); }
}


#END MAIN

sub displayHelp
{
my $h=<<END;
Usage: 	art [--push][--pull][--sync]

Use this utility to synchronize art files for project-eva between your computer
and Dropbox. Uses system last modified time to attempt to keep newest copies of files.

	push 	Push your local changes to the art to Dropbox
	pull 	Pull changes from Dropbox to your local copy of the game
	sync 	Shorthand for a pull, then a push

END

	print $h;
	exit;
}

sub doArtPush
{
	# TODO: IMPLEMENT THIS
	$DBPATH = getDBDir();
	$ASSETSDIR = catdir($DBPATH, "Assets");
	print "ERROR: Not implemented yet\n";
}

sub doArtPull
{
	$DBPATH = getDBDir();

	$ASSETSDIR = catdir($DBPATH, "Assets");
	`cp -rv \"$ASSETSDIR\" .`;
	print "Art pulled from Dropbox\n";
}

sub touchConf
{
	# Check if dropbox has been configured
	if( ! -e 'box.conf' ) {
		# Create the conf file
		`touch box.conf`;
		# Check the default directory
		if( -d "~/Dropbox/project-eva" ) {
			`echo ~/Dropbox/project-eva > box.conf`;
		} else {
			promptEnterDBFolder();
		}
	}
}

sub getDBDir 
{
	touchConf();
	open my $CONF, "box.conf" or die "Couldn't find your box.conf file!";
	$DBPATH = <$CONF>;
	chomp($DBPATH);
	$DBPATH = realpath($DBPATH);

	if( ! -d $DBPATH ) {
		print "I couldn't find your Dropbox folder. Did you edit box.conf?";
		exit 1;
	}
	return $DBPATH
}

sub promptEnterDBFolder
{
	print "Before we continue, I need the absolute path\nto your project-eva Dropbox folder.\n";
	print "EX: C:\\Users\\Alex\\Dropbox\\project-eva\\\n";

	$found = 0;
	while($found < 1) {
		print "PATH:\t";
		$DBPATH = <STDIN>;
		chomp($DBPATH);
		$DBPATH = realpath($DBPATH);

		if( -d $DBPATH ) {
			$found += 1;
			`echo $DBPATH > box.conf`;
		} else {
			print "\nSorry, I couldn't find that path. Try again";
		}
	}
}