#!/bin/perl
use File::Spec::Functions;
use File::Basename;
use File::Copy;
use Cwd 'realpath';

require '.git/hooks/functions.pl';

touchConf();
$DBPATH = getDBDir();

@STAGED = `git diff-index --cached --name-only HEAD`;
@FILETYPES = getFileTypes();

foreach( @STAGED ) {
	my $file = $_;
	chomp($file);
	my ($ext) = $file =~ /(\.[^.]+)$/;
	foreach(@FILETYPES) {
		my $type = $_;
		if( $ext eq $type ) {
			my $DIRNAME = dirname($file);
			my $BASENAME = basename($file);

			my $DESTPATH = catdir($DBPATH, $DIRNAME);
			`mkdir -p \"$DESTPATH\"`;

			my $DEST = catdir($DESTPATH, $BASENAME);
			move($file, $DEST);

			`git reset HEAD $file`;
			`touch \"$file\"`;
			open(my $F, ">>$file") or die "Couldn't reopen touched file during commit";
			$DATE = `date`;
			print $F $DATE;
		}
	}
}
# Add all of the new placeholder files
`git add .`;